language: swift
osx_image: xcode10.1
os: osx

script:
  set -o pipefail &&
  travis_retry
  xcodebuild build
  -workspace CotEditor.xcworkspace
  -scheme CotEditor
  -destination 'platform=macOS'
  CODE_SIGN_IDENTITY=""
  CODE_SIGNING_REQUIRED=NO
  | xcpretty